# Generated by Django 5.2 on 2025-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_blogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
