# Generated by Django 5.2 on 2025-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_blogs_blog_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='No Title Given', max_length=255),
        ),
    ]
