# Generated by Django 5.2 on 2025-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_blogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.TextField(),
        ),
    ]
